services:
  mysql:
    image: mysql:8.0
    container_name: mysql-workshop
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: workshopdb
      MYSQL_USER: workshopuser
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    networks:
      - workshop-net
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  workshop-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local